spring:
  datasource:
    url: jdbc:mysql://localhost:3306/guyuning
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
